### ISSUE TITLE
Release Checklist

### ISSUE THREAD

**Issue by vache** [vache/BuildingEditor#13]
Release for single omt sized editor:
- [x] Group... grouping.  Make contiguous instances of groups into a single rectangle for json output.  Use system similar to old design, make list of groups and a map of groupname->array of indices where the group exists, then step through the arrays and make a combined rectangle of the area.
- [x] Toilets.  Pretty basic.
- [x] Basic instruction guide.
- [x] Make the data path not hardcoded - use QFileDialog to get the filename as soon as software starts.  Possibly use QSettings to keep track of last path selected.
- [x] Tooltips where relevant - modded items should have the mod in the tooltip, all of the buttons and options in the object editors.
- [x] Prompt on write for overmap terrain & weight, until better system is ready - use QInputDialog to grab these values on write without having to write something more robust.
- [x] Clear tiles option for furniture/vehicles/items/etc.
- [X] Feedback for setting the nondrawable items - ~~message in statusbar~~ or some sort of highlight.
- [x] Export the traps.
- [x] Make export "Write" file dialog automatically try to force .json filename, also, select the user inputted "data" ~~(or data/json/mapgen)~~ directory as the target location.
- [x] Figure out how to deploy correctly in stupid qt.

Optional:
- [ ] Status bar updates when things change.
- [x] Reset option - set the whole model back to blank everything.
- [ ] Work out line drawing for walls.
- [ ] Possibly check and enforce placement rules (NOITEM tags on furn/terrain, use movecost=0 on terrain or movecostmod=-1 on furn to prevent monster placement)
- [ ] Light up tiles that are selected with rubberband tool - set indices in rubberband area as selected for blue highlight.
- [ ] Prettify the json, use multiple documents to set some fields as compact, and to get the layout of the generated jsons close to the handmade jsons.
- [ ] Search box for features.  Pain in the ass trying to find a specific entry in the list sometimes.
