### ISSUE TITLE
Release 2 Checklist

### ISSUE THREAD

**Issue by vache** [vache/BuildingEditor#19]
- [ ] Tooltips where appropriate.
- [ ] Finalize OMT data and dialog.
- [ ] "Select" tool, and way to edit existing tile data.
- [ ] Fix the menus, add a help window, and maybe add an about page
- [ ] Revisit placement rule enforcement
