### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by vache** [vache/BuildingEditor#20]
- [x] Rotate setting needs to propagate through from special settings to individual OMT
- [x] If special is marked as rotate, the OMT IDs should have _north appended on them
- [x] Empty OMT datas should not be exported
- [x] Exported OMT datas should have correct ID
- [ ] Tile editor
- [ ] JSON writing should reuse directories
- [ ] JSON object writing, objects should have a ToJson method like the data objects
- [ ] JSON writer code should be more cohesive in general
- [ ] JSON output should be as close to current format as possible
- [ ] Correct some design elements, like passing data around from the wizard
- [ ] Create "Edit" windows to edit omt and special data
- [ ] Fix up menus
- [ ] Linux build
- [x] Occurrences and max city distance not working correctly
- [ ] Special connections, and ui for them
- [x] Drawing up/down connections and walls
- [ ] Undo stack
- [ ] Rotate/flip
- [ ] Layers
- [ ] Draw vehicle size
- [ ] Check for invalid tiles on export
- [ ] Split items into collapsible categories
- [ ] Crash when clicking "select" at search results without a search result clicked
- [ ] Crash when move slider to z-10 in main view
- [ ] Tile support... one day...
